package.json, src/browserify.js, src/imports.js, src/processor.js, src/relative.js, test/browserify.js, test/processor.js, test/results/browserify-avoid-duplicates.css, test/results/browserify-factor-bundle-a.css, test/results/browserify-factor-bundle.css, test/specimens/factor-bundle-a.css, test/specimens/factor-bundle-a.js, test/specimens/factor-bundle-b.js, test/specimens/factor-bundle-common.js, test/specimens/local.js
Now able to map `factor-bundle` bundles to CSS dependencies, dedupe, and extract common dependencies amongst the bundles (and common files).
**NOTE**: `modular-css` must be added as a plugin **BEFORE** `factor-bundle` for it to work. Browserify limitation, sadly.
Example:
```js
var build = browserify([
"./test/specimens/factor-bundle-a.js",
"./test/specimens/factor-bundle-b.js"
]);
build.plugin("modular-css", {
css : "./test/output/browserify-factor-bundle.css"
});
build.plugin("factor-bundle", {
outputs : [
"./test/output/factor-bundle-a.js",
"./test/output/factor-bundle-b.js"
]
});
build.bundle(function(err, out) {
...
});
```
=> Support factor-bundle plugin

src/browserify.js, src/plugins/scoping.js, src/processor.js, test/browserify.js, test/plugin-scoping.js, test/processor.js, test/results/browserify-namer-fn.css, test/results/browserify-prefix.css
Ensure that `prefix` strings and `namer` functions can make it all the way from browserify through the processor and into the scoping plugin.
=> Custom naming

src/plugins/composition.js, test/plugin-composition.js
- decl.prev() seems a bit wonky, may need to rethink that check. Seems
to work for now though.
- Added some tests to make sure that it works with global(...)
- Minor optimization, only call unique once per selector we're
outputting instead of every single time they're composed.
=> Actual tests for multiple composes statements

src/plugins/scoping.js, test/plugin-composition.js, test/plugin-keyframes.js, test/plugin-scoping.js, test/processor.js, test/results/browserify-avoid-duplicates-local.js, test/results/browserify-avoid-duplicates-start.js, test/results/browserify-avoid-duplicates.css, test/results/browserify-export-all-identifiers.json, test/results/browserify-export-identifiers.js, test/results/browserify-fb-basic-a.css, test/results/browserify-fb-basic.css, test/results/browserify-fb-noempty-a.css, test/results/browserify-fb-relative-a.css, test/results/browserify-include-css-deps.css, test/results/browserify-include-css-deps.js, test/results/browserify-relative.css, test/results/processor-avoid-duplicates.css, test/results/processor-output-all.css, test/results/processor-relative.css
- Because a CSS class can't start with a number, lol.
- Update tests for new hash format
=> Prefix hash with "mc" so it's always valid

package.json, src/plugins/scoping.js, test/plugin-composition.js, test/plugin-keyframes.js, test/plugin-scoping.js, test/processor.js, test/results/browserify-avoid-duplicates-local.js, test/results/browserify-avoid-duplicates-start.js, test/results/browserify-avoid-duplicates.css, test/results/browserify-export-all-identifiers.json, test/results/browserify-export-identifiers.js, test/results/browserify-fb-basic-a.css, test/results/browserify-fb-basic.css, test/results/browserify-fb-noempty-a.css, test/results/browserify-fb-relative-a.css, test/results/browserify-include-css-deps.css, test/results/browserify-include-css-deps.js, test/results/browserify-relative.css, test/results/processor-avoid-duplicates.css, test/results/processor-output-all.css, test/results/processor-relative.css
Hasha was spitting out md5 of the contents, this uses murmur and hashes the file path. Should be faster and the output's half the size!
Fixes #22
=> Use unique-slug instead of hasha

src/browserify.js, test/browserify.js, test/results/browserify-fb-deps-a.css, test/results/browserify-fb-deps.css, test/specimens/browserify-fb-deps-a.js, test/specimens/browserify-fb-deps-b.js, test/specimens/browserify-fb-deps-common.js
The test for which files to include in the common bundle had some issues, it would skip files that only appeared in common JS files.
So now it only excludes files that appear in a single bundle, which is the original intention anyways.
This PR also adds a small test helper that cleans up a bunch of test cases for browserify.
=> Fix missing files when using factor-bundle

package.json, src/browserify.js, test/browserify.js, test/results/watchify-1.css, test/results/watchify-2.css, test/specimens/blue.css, test/specimens/watchify.js
Processor objects don't re-process the same files, so we were always building based on the first time we saw any file.
Now, it'll create a new Processor instance every time `bundle()` is called. This may be a bit inefficient, but it's more correct behavior.
Would be nice to see about hooking into watchify's update notifications so we could invalidate our processing cache based on the changed files and have the best of both worlds. Someday!
=> Fix watchify caching

src/browserify.js, src/processor.js
So that whenever watchify sees an update we can purge cache entries w/o having to re-create everything on every call to `browserify.bundle()`.
Fixes #30
=> Add processor.remove & use in browserify

src/processor.js, test/browserify.js, test/results/watchify-relative.css, test/specimens/relative.css, test/specimens/watchify-relative.css, test/specimens/watchify-relative.js
Need to clone parsed nodes before rewriting relative URLs, otherwise they can be processed multiple times. Probably a bit slower.
Fixes #35
=> Fix + tests for #35

package.json, src/processor.js, test/processor.js
So you can do
```js
new Processor({
after : [ require("postcss-import") ]
})
```
and suddenly `@import` calls in your CSS are inlined, but haven't been rewritten.
=> Add before/after options for running postcss plugins

src/plugins/composition.js, test/issue-56.js
Fixes #56
When a declaration like
```css
.fooga { composes: booga; }
```
is found now the code makes a note of the selector, checks all the declarations in the file to see if that selector is used elsewhere, and then if it's only used in that one place it's deleted. This probably has some edge cases around other stuff that I'm not thinking of, but seems pretty conservative and safe to my mind.
=> Only remove if selector isn't used again

src/processor.js, test/issue-66.js
Fixes #66
Filter all files passed into `Processor.remove()` by checking to ensure that they're part of the dependency graph.
=> Don't explode on unknown files in remove() calls

README.md, bin/cli.js, src/browserify.js, src/processor.js, test/issue-24.js, test/processor.js, test/results/processor/start.css
This renames `.css()` to `.output()` and will actually let the `after` plugins process the entire CSS output. It also returns a PostCSS `Result` or `LazyResult` instead of just a string so it's easier to do more processing or interesting things with it.
This is a breaking API change, and will lead to `0.11.0` wheeeeee.
=> Rename .css() & fix up after

bin/cli.js, src/processor.js, test/processor.js, test/results/processor/source-map.css
Fixes #73 
Only real problem was that options weren't always being merged correctly when running through postcss. That is fixed by this PR.
This also defaults the CLI to outputting inline source maps, because that seems really useful.
Tests to follow when it's not so late. :sleepy:
=> Fix up sourcemaps

src/browserify.js, test/browserify.js, test/results/browserify/source-maps.css
And automatically specify sourcemap supports when it's `true`.
Fixes #77
=> Respect browserify debug option

src/processor.js, test/results/issues/58.css, test/results/processor/output-all.css
Makes output stable, despite the order browserify/watchify/etc add files. Was seeing spurious commits where files looked changed, but only because they had their sections re-ordered.
=> Sort output before generating

package.json, rollup.js, src/rollup.js, test/exports.js, test/results/rollup/simple.css, test/results/rollup/simple.js, test/rollup.js, test/specimens/rollup/simple.css, test/specimens/rollup/simple.js
Pretty basic atm, but rollup doesn't support much yet! No need to support output splitting, watching, or anything else exotic yet that I've seen. Should be easy to add once those exist assuming the plugin API provides reasonable hooks.
Their story around outputting non-rollup managed files is a little clunky at the moment, see https://github.com/rollup/rollup/pull/353 for details on the workaround being used (`footer` lifecycle fn that doesn't return a string). It's a bit weird since the output from modular-css is async and `footer` is expected to be sync, but it'll work well enough.
=> First pass at rollup plugin

src/plugins/composition.js, test/browserify.test.js, test/composition.test.js, test/issue-98.test.js, test/lib/compare-files.js, test/processor.test.js, test/results/browserify/avoid-duplicates-local.js, test/results/browserify/avoid-duplicates-start.js, test/results/browserify/include-css-deps.js, test/results/issues/56.css, test/results/issues/98.css
Rules that only compose something else are stripped from the CSS, but are left in the exports object. I don't see a compelling reason to remove them and it simplifies this code a lot.
Fixes #98
Example:
```css
.fooga { color: red; }
.wooga { composes: fooga; }
```
Outputs this css:
```css
.abcd123_fooga { color: red; }
```
and this JS
```js
module.exports = {
"fooga" : "abcd123_fooga",
"wooga" : "abcd123_fooga abcd123_wooga"
};
```
where before the JS output would have `wooga` just be `abcd123_fooga`.
=> Remove export stripping

README.md, register.js, src/register.js, test/exports.test.js, test/register.test.js, test/results/register/start.css
Runs the scoping plugin by itself, since that can run synchronously. Also processes files in the background and writes them out as it can using a processor intstance.
Fixes #95
=> Add require() hook to load css

src/browserify.js, test/issue-105.test.js, test/results/issues/105.css, test/specimens/issues/105/1.css, test/specimens/issues/105/folder/2.css
Browserify transforms seem unresolved symlink paths, but the "deps" pipeline sees resolved paths. This led to no end of hilarity. Fixed this by making sure to manually resolve symlinks during the transform stage so the dependency graph is functional.
Tests are disabled though because I don't have a POSIX system handy, and Git for Windows can't submit symlinks :disappointed:
Fixes #105
=> Fix symlinked files w/ browserify

src/rollup.js, test/results/rollup/simple.js, test/results/rollup/tree-shaking.js, test/rollup.test.js, test/specimens/rollup/simple.js, test/specimens/rollup/tree-shaking.css, test/specimens/rollup/tree-shaking.js
So tree-shaking can do its thing and reduce the size of the bundle. Huge props to @iAdramelk for doing the majority of the work in #113, I just reformatted a bit and added an extra test case.
=> Rollup exports individual declarations as well

.jscsrc, package.json, src/rollup.js, test/results/rollup/invalid-name.js, test/rollup.test.js, test/specimens/rollup/invalid-name.css, test/specimens/rollup/invalid-name.js
The changes in #114 had one pretty serious issue, if any of the CSS classes were not valid JS identifiers they would still be output and then generate invalid JS.
Now any invalid identifiers are skipped, and a warning is emitted.
CC @iAdramelk
=> Only export valid identifiers from rollup plugin

package.json, src/_clone-graph.js, src/_sequential.js, src/processor.js, test/processor.test.js, test/results/issues/58.css, test/results/processor/sorting.css, test/specimens/composes.css, test/specimens/deep.css, test/specimens/folder/folder2.css, test/specimens/folder/subfolder/subfolder.css
By traversing the dependency graph, finding all the leaf nodes, removing them, then continuing until we've pruned the entire tree. Also sorting each tier alphabetically to help keep things stable no matter the add order.
Fixes #119
=> Output in stable order

src/plugins/scoping.js, test/scoping.test.js
Now it runs through all pseudo selectors first, converting :global() to local w/o transforming the name. Then it goes through and transforms everyone else.
Fixes #131
=> Rework scoped selector plugin

package.json, src/browserify.js, src/processor.js, test/processor.test.js, test/specimens/invalid-import.css
Strict mode is the default, and treats any warnings from plugins when processing files as an error and blows up. This check occurs on all three lifecycle methods, so it may trigger multiple times if you have bad files causing the `before` hook to explode.
Disable strict mode by setting `strict : false` in options passed in.
Fixes #82
=> Add strict mode concept

src/browserify.js, src/lib/relative.js, src/processor.js, src/rollup.js
Mostly so `rollup --watch` monitors the files correctly. Those deps will be tree-shaken out anyways since nothing else references them.
Also adds a central place to create path-friendly relative paths, because browserify AND rollup doing it in code was stupid.
=> Include dependencies in transform output

package.json, src/rollup.js, test/rollup.test.js
Now that rollup/rollup#742 & rollup/rollup#773 have landed the terrible `footer` hack can finally be banished!
This also gives the rollup plugin a `name` field because IIRC that is becoming important soon.
=> Use rollup ongenerate & onwrite hooks

src/rollup.js, test/glob.test.js, test/lib/warn.js, test/processor.test.js, test/rollup.test.js
Make sure that warnings (in strict mode) from plugins are actually bubble all the way up to the proper Promises in rollup.
Previously if a `done` plugin was throwing warnings they'd just be silently ignored, which is terrible.
=> Better handle errors within rollup

package.json, src/lib/promise.js, src/lib/sequential.js, src/processor.js, test/lib.sequential.test.js, test/lib/wait.js, test/processor.test.js
`node@4.x` is where it's at, so dropping support for a `Promise` polyfill to streamline the package.
=> Remove Promise polyfill

README.md, src/glob.js, test/glob.test.js, test/results/glob/glob-excludes.css, test/results/glob/glob.css
Using the same cwd indicator for both `Processor` and `.glob()` reduces issues when dealing with junctions and makes it less likely to be misused
BREAKING CHANGE:
`dir` is no longer accepted as a property when invoking `.glob()` and will be ignored.
=> refactor: use cwd for .glob()

src/lib/composition.js, src/plugins/composition.js, test/lib.composition.test.js, test/plugin.composition.test.js
Fixes #184 by no longer accidentally overwriting the global w/ the local
ref.
Also!
- Clean up some composition lib repetition
- Verify the issue isn't in the composition lib
- Add failing test for #184
=> Re-work reference storing so globals are prefixed

src/processor.js, src/rollup.js
#158 is because `rollup-watch` never tells the plugin which files have changed. This does some gross stuff to make it work which probably has bad edge-cases that lead to bloated bundles.
But at least it regenerates the CSS when a file changes! 😒
=> Hack in rollup-watch support

src/plugins/scoping.js, test/plugin.scoping.test.js
It's fine to re-use a selector normally, because it'll be always be transformed to the same name.
```css
.fooga { color: red; }
.fooga:hover { color: blue; }
/* becomes */
.abc123_fooga { color: red; }
.abc123_fooga:hover { color: blue; }
```
but when you introduce `:global()` things get more complicated, since those are **not** renamed.
```css
.fooga { color: red; }
:global(.fooga) { color: blue }
/* becomes */
.abc123_fooga { color: red; }
.fooga { color: blue }
```
which looks fine, until you consider the mapping object that creates.
```js
{
fooga : "fooga",
}
```
since the `:global()` came second and the names overlap it blows up any existing definition. It could also blow up the other way if the global came first.
That's bad for user expectations, so make it such that globals & …
=> Throw if a selector is used locally and globally

src/plugins/graph-nodes.js, test/plugin.graph-nodes.test.js
Since the parser wasn't in a `try`/`catch` block errors weren't nice PostCSS errors with proper locations and file names. Fixed now so that you can actually figure out wtf broke.
=> Fix error reporting in initial walk of graph

docs/webpack.md, package.json, src/webpack-plugin.js, test/webpack.test.js
Instead of writing my own files to disk using `fs`, take advantage of webpack's `compiler.assets` object and add assets there instead.
Not *technically* a breaking change, though very likely to cause breakage.
=> Use webpack's built-in assets support

src/lib/graph-tiers.js
Instead make way over-complicated keys by comparing almost every field of the `stat` object.
Because `stats.ino` is a lie on windows.
Bah.
Fixes #242
=> Don't use inodes for de-duping

package.json, src/plugins/keyframes.js, src/plugins/values-replace.js, test/issue-24.test.js, test/issue-56.test.js, test/issue-98.test.js, test/plugin.scoping.test.js, test/plugin.values-replace.test.js, test/processor.options.test.js, test/processor.test.js
Instead of matching on whole `word` blocks, match each `word` block w/ a regex composed of all available `value` names.
Fixes #245
=> Smarter value matching

package.json, src/plugins/externals.js, src/plugins/graph-nodes.js, src/plugins/values-composed.js, src/plugins/values-namespaced.js, src/processor.js, test/plugin.externals.test.js, test/plugin.graph-nodes.test.js, test/plugin.values-composed.test.js, test/plugin.values-namespaced.test.js, test/plugin.values-replace.test.js, test/processor.methods.test.js
Fixes #246 
This is an implementation of the [proposal](https://github.com/tivac/modular-css/issues/246#issuecomment-280084923) in #246 of a way to specify multiple `resolver` functions for resolving file paths. Previously there was a single, hardcoded resolver that simply used the node resolution algorithm. The new method takes an array of potential resolvers and runs them in order until a non-falsey result is achieved. This matches very closely with how [rollup](https://github.com/rollup/rollup/wiki/Plugins#creating-plugins) handles 3rd party resolution and seems like a useful pattern to adopt.
I briefly toyed w/ the idea of making it compatible w/ rollup resolver plugins but decided it was too weird and unlikely to work.
This PR **does not** introduce any custom `resolvers`, it simply …
=> feat: Add support for custom resolvers

.dangerfile.js, src/processor.js, src/webpack-loader.js, test/issue-248.test.js, test/specimens/issues/248/index.css, test/specimens/issues/248/index.js
Fixes #248 
When a loader calls the callback with an error, webpack apparently just marks it and continues on its merry way. This meant that `processor.output()` was being invoked with an incomplete set of `._files` since it assumed that errors would bail on whatever was using it.
It now filters out invalid `._files` entries before trying to process them. Not sure that's the right behavior, but it does prevent this particular explosion. If someone w/ more webpack experience wants to explain a better way to handle this I'm all 👂s!
=> fix: barf in a nicer manner for webpack

package.json, packages/core/plugins/keyframes.js, packages/core/test/keyframes.test.js
Otherwise the regex ends up broken and matches everything, then replaces
everything with nothing because there's no way it could match.
Fixes #256
=> fix: early-out from keyframe renaming if no work to do

packages/rollup/package.json, packages/rollup/rollup.js, packages/rollup/test/results/rollup/watch1.css, packages/rollup/test/results/rollup/watch2.css, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/rollup/watch.js
A slightly hacky fix I introduced to work around #158 ended up finally having some consequences, so going back to the other hacky fix which should be a bit safer.
Fixes #265
=> Fix dependencies going missing with rollup

packages/core/processor.js, packages/core/test/processor.test.js, packages/postcss/postcss.js, packages/postcss/test/postcss.test.js
PostCSS plugins can get options two ways, previously `postcss-modular-css` only really supported one of those ways for the `json` option. Now it supports both.
Also exposed the already-merged `processor.options` value as a getter because it simplified this.
See #270 for the original issue.
=> More flexible postcss support for options

packages/core/plugins/composition.js, packages/core/test/__snapshots__/plugin.composition.test.js.snap, packages/core/test/plugin.composition.test.js
Fixes #273 
Also loop through EVERY previous declaration, just in case. Doing a bit more work but it's probably worth it to ensure nothing nasty is sneaking in.
=> fix: allow comments before composes in a rule

packages/webpack/loader.js, packages/webpack/package.json, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/specimens/es2015-default.js, packages/webpack/test/specimens/es2015-missing.js, packages/webpack/test/specimens/es2015-named.js, packages/webpack/test/specimens/es2015.css, packages/webpack/test/specimens/invalid-name.css, packages/webpack/test/specimens/invalid-name.js, packages/webpack/test/webpack.test.js
This is mostly a copy/paste of the rollup code. It could be extracted out into some sort of shared package but it's just different enough to not make it worth that work.
@TrySound, this about what you were looking for?
Fixes #280
=> Use ES2015 exports in webpack

packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js
`rollup-watch` test had some bad formatting that was preventing the tests from actually running (still passing ok though wtf?)
Related to #288 but doesn't necessarily solve that issue.
=> test: fix broken snapshots

packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/specimens/change.js, packages/webpack/test/specimens/watch.js, packages/webpack/test/webpack.test.js
This is a copy of the very brute-force approach the rollup plugin takes, it simply throws away the entire Processor instance after each run. There may be a better way to handle this within webpack (`watchify` fires very useful file change events we can use to precisely purge the cache, for instance) but for now this will remove a lot of badness at the cost of some speed.
cc @TrySound 
Fixes #290
=> Fix webpack watch cache staleness

packages/webpack/README.md, packages/webpack/loader.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/webpack.test.js
Fixes #294
If you're using node or need to use CommonJS for some reason and don't want to deal with `require("./file.css").default` (I don't blame you) then set `options: { cjs : true }` in your loader config and bask in the un-treeshakeable blob of data that is attached to `modular.exports`!
=> Add cjs webpack loader option

packages/core/processor.js, packages/core/test/api.test.js
It's unnecessary, the dependency graph can already tell us what files need to be removed. This code looks more complex but is both a little faster and way more straightforward to follow after a bit of reading.
=> Remove recursion during .remove()

packages/webpack/loader.js, packages/webpack/plugin.js
The changes in #293 work great for the mode where `webpack.run()` is being called over and over again.
Unfortunately they're super broken for webpack's actual watch mode.
So now those two are split apart, following a [convention in the webpack codebase](https://github.com/webpack/webpack/blob/b2a6085d9684cb8bb3c47cbcb778413844d70d53/lib/CachePlugin.js#L30-L33). It seems kinda hacky but now in watch mode it can use fine-grained `invalid` events to remove files from the cache and in non-watching mode it can use the coarser `.fileTimestamps` property and now all the tests actually pass and oh god I'm so tired 😪
=> Fix webpack by breaking apart watching/non-watching modes

packages/browserify/browserify.js, packages/browserify/test/__snapshots__/issue-313.test.js.snap, packages/browserify/test/issue-313.test.js, packages/browserify/test/specimens/issues/313/1.css, packages/browserify/test/specimens/issues/313/2.css
This is a slight reworking of #314 to make it the default watchify test for caching since clearly the previous version wasn't working.
Also includes some other cleanup in the watchify tests, as well as some saner places for files to live in order to keep things clean-ish.
Fixes #314 
Fixes #313
Hey @darthmaim would you take a look to verify that I didn't do anything stupid here?
=> Fix bad browserify options references

lerna.json, packages/aliases/.npmignore, packages/aliases/LICENSE, packages/aliases/README.md, packages/aliases/aliases.js, packages/aliases/package.json, packages/aliases/test/__snapshots__/aliases.test.js.snap, packages/aliases/test/aliases.test.js, packages/aliases/test/specimens/one/one.css, packages/aliases/test/specimens/one/sub/sub.css, packages/aliases/test/specimens/two/two.css, packages/paths/README.md, packages/paths/package.json, packages/paths/paths.js
README lays out the case for this, but basically it's a way to make simple named aliases to complex/long/ugly filepaths.
Instead of 
```
@value foo from "../../../../../../../../some/other/directory/file.css";
```
You can alias `directory` to that path, and do this
```
@value foo from "directory/file.css";
```
=> Aliases resolver

docs/api.md, packages/core/processor.js, packages/core/test/__snapshots__/api.test.js.snap, packages/core/test/api.test.js
See #324 for an example of how this can bite you currently. Also adds documentation on `Processor` methods/properties so that this gotcha can be called out in the docs that now exist.
=> Reject calls to .output() if file processing isn't complete

packages/core/plugins/values-export.js
Messages with field `plugin` unfortunately are not standard so relying on this field can lead to problems like `Cannot read property 'search' of undefined`
E.g https://github.com/postcss/postcss-import#dependency-message-support
=> fix "Cannot read propoerty 'search' of undefined"

docs/rollup.md
Not sure if you want this to be added to the docs but it took me way too long to figure out why I was getting `Unexpected token (1:0)` errors when running Rollup.
Even if you don't accept it, I hope it might help some future user searching for a solution to stumble upon this PR.
=> Add a hint to the example Rollup config to avoid Unexpected Token error

docs/rollup.md
Small tweak for the Rollup docs: the plugin for Rollup now has it's own package `modular-css-rollup`.
=> Rollup docs: plugin name has been renamed

packages/browserify/test/browserify.test.js, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/rollup/watch.js, packages/rollup/test/specimens/watch.js
Fixes #345
Turns out that `rollup-watch` only calls `transform` for files that changed (were purged from the `cache` object), so only changes files exist in the second pass on a bundle. That's... bad.
Instead go back to remove dependencies and re-processing if they're "new", but only after the first run. Still feels kludgey but seems to work ok after cleaning up the watch test to be a bit more interesting.
=> feat: revert #266 to be more like #158

packages/core/plugins/externals.js, packages/core/test/__snapshots__/externals.test.js.snap, packages/core/test/__snapshots__/values.test.js.snap, packages/core/test/specimens/externals.css
Same issue as in #277, https://github.com/postcss/postcss-selector-parser/pull/105 should fix it hopefully. Not out yet and want to Fix #342 so using the same workaround for now.
=> fix: Multiple :externals() should work

docs/features.md, packages/cli/test/cli.test.js, packages/core/parsers/parser.js, packages/core/parsers/parser.pegjs, packages/core/plugins/values-export.js, packages/core/plugins/values-imported.js, packages/core/processor.js, packages/core/test/__snapshots__/values.test.js.snap, packages/core/test/specimens/value-export.css, packages/core/test/specimens/value-import.css, packages/core/test/values.test.js
As requested by @getkey in #354, you can now do `@value * from "./file.css"` and it'll import any `@value` definitions from `file.css` into the current file. Importantly, those definitions will also be **exported** from the current file, so you can use this feature as a way to build layered theming.
Local `@value`s will override any imported `@value`s with the same name, so that should work as expected. My test case is pretty simple but I think it covers the main points.
Here's the example from the docs:
You can also import all the `@value` definitions from another file into the current one. The imported `@value`s will also be exported from that file, allowing for simple theming setups with overriden colors/dimensions/etc.
```css
/* colors.css */
@value main: red;
@value bg: white;
``` …
=> feat: @value imports

.travis.yml, package-lock.json, packages/browserify/test/__snapshots__/issue-58.test.js.snap, packages/browserify/test/issue-58.test.js, packages/browserify/test/specimens/issues/58/1.css, packages/browserify/test/specimens/issues/58/2.css, packages/cli/test/cli.test.js, packages/core/plugins/values-replace.js, packages/core/test/__snapshots__/values.test.js.snap, packages/core/test/specimens/value-namespace.css, packages/core/test/specimens/values.css
Fixes #363 by sorting values by length so that longer replacements match first.
A little hacky-feeling, but seems ok after thinking about it for a bit.
This commit also solves the recurring travis failures I've been seeing thanks to a [tip from @darthmaim in gitter](https://gitter.im/modular-css/modular-css?at=5a08ca87505b630c05d4d848).
=> Overlapping value replacement

packages/core/processor.js, packages/core/test/__snapshots__/api.test.js.snap, packages/core/test/api.test.js
This will enable fixing of #353 once the changes to `modular-css-rollup` lands.
=> feat: processor.remove returns removed files

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js
Fixes #353 
Depends on #376 (which was cherry-picked out of this branch, I know it's weird)
Change rollup logic to re-add all the files that were removed instead of just the one that was changed.
=> fix: rollup watching loses file contents

docs/features.md
Added clarification of how `:global()` should be used with comma separated rules, and recommendation for when large amounts of comma separated rules are used e.g. in resets. As discussed in [#395](https://github.com/tivac/modular-css/issues/395)
=> docs: `:global()` reset clarification

packages/rollup/package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/specimens/named.css, packages/rollup/test/specimens/named.js, packages/rollup/test/specimens/simple.css, packages/svelte/package.json, packages/svelte/test/__snapshots__/rollup.test.js.snap, packages/webpack/loader.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/specimens/es2015-named.js, packages/webpack/test/specimens/es2015.css
Noticed this when upgrading, the change to export `@value`s alongside classes in #398 caused a bug in my webpack/rollup code to become more obvious.
They were generating code like this:
```js
export var a = ""b"";
```
since when you write `@value a: "b"` the literal value of `a` is `"b"`, and I don't convert that to an unquoted string during the output process. Now it's using `JSON.stringify(...)` when exporting ALL values, which should be safer.
It may be worth adding support later for stripping the extraneous-seeming quotes off of `@value`s that are solely `"quoted strings"` but I'm not touching that for now.
=> Correctly support named exports of  @value

packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/webpack.test.js
Somehow this was never tested before?
Also make sure that errors from the plugin propagate correctly.
This fixes an error that @chiel and @getkey reported in [gitter](https://gitter.im/modular-css/modular-css?at=5a8bffc5888332ee3aa9acad).
=> fix: webpack inline maps should work

docs/api.md, docs/extending.md, packages/core/lib/output.js, packages/core/processor.js, packages/core/test/__snapshots__/options.test.js.snap, packages/core/test/__snapshots__/values.test.js.snap, packages/core/test/issues/__snapshots__/issue-24.test.js.snap, packages/core/test/options.test.js
Based on a request from @AndrewLeedham in #401, this new lifecycle hook allows for modifying the exports of a CSS file by pushing a specifically crafted message onto the messages array. Details are in the new extending.md document which also conveniently exists now to better document lifecycle hooks and what they're good for.
Planning on shipping this for `8.1.0` unless someone really hates the name and lets me know pretty quickly, it's a pretty harmless change that could allow some interesting new approaches.
=> Allow plugin exports via "processing" lifecycle hook

docs/webpack.md, packages/webpack/loader.js, packages/webpack/package.json, packages/webpack/test/__snapshots__/simple.json
This PR fixes API changes introduced in Webpack 4.
=> fix: webpack 4

.travis.yml, package-lock.json, package.json, packages/rollup/README.md, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/manual-chunks/a.css, packages/rollup/test/specimens/manual-chunks/a.js, packages/rollup/test/specimens/manual-chunks/b.css, packages/rollup/test/specimens/manual-chunks/b.js, packages/rollup/test/specimens/manual-chunks/c.css, packages/rollup/test/specimens/manual-chunks/c.js, packages/rollup/test/specimens/no-css.js, packages/test-utils/exists.js
This takes advantage of the new plugins APIs introduced in https://github.com/rollup/rollup/pull/2208
`modular-css-rollup` will now support automatic chunks via multiple `inputs` and manual chunking of vendor files via `manualChunks`. It might also support dynamic `import` but I haven't written tests for that yet.
This is a :warning: **BREAKING CHANGE** :warning:, it will only be compatible with `rollup@0.60` and higher.
=> feat: add support for Rollup 60

docs/svelte.md, packages/svelte/README.md, packages/svelte/src/markup.js, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/invalid-external-script.html, packages/svelte/test/specimens/invalid-external-template.html, packages/svelte/test/specimens/invalid-inline-script.html, packages/svelte/test/specimens/invalid-inline-template.html, packages/svelte/test/specimens/invalid.css, packages/svelte/test/svelte.test.js
Also adds strict mode which will throw errors on missing keys.
=> feat: emit warnings on missing keys

docs/svelte.md
Small doc fix.
Spelled "Svelte" wrong in branch 😞
=> Add missing quotes

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup-watch.test.js.snap, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup-watch.test.js, packages/rollup/test/rollup.test.js
When working on #449 I got annoyed at how many times I was having to check `common.css` in cases where it wasn't actually necessary.
So now I've done something about it. `modular-css-rollup` will only create a `common.css` if there's more than one CSS bundle being generated which is how it should've been all along.
=> fix: tighten up rollup bundles

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js
Fixes #455 
This won't handle `[hash]` but I have no idea what I could possibly do there in that instance, because rollup won't tell me the filename ahead of time (since it can't get the hash until it has the contents, an annoying 🐔 and 🥚 problem).
=> fix: External map references

packages/svelte/package.json, packages/svelte/src/markup.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/svelte.test.js
Fixes #462 by ensuring that in cases where the same `preprocess` is run against a file multiple times (like when using `modular-css-svelte` with `modular-css-rollup` in `--watch` mode) it'll pick up any changes w/o having to restart the watcher.
=> fix: remove files when re-preprocessing for svelte

package-lock.json, package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/specimens/common-splitting/a.css, packages/rollup/test/specimens/common-splitting/a.js, packages/rollup/test/specimens/common-splitting/b.css, packages/rollup/test/specimens/common-splitting/b.js, packages/rollup/test/specimens/common-splitting/c.css, packages/rollup/test/specimens/common-splitting/c.js, packages/rollup/test/specimens/common-splitting/shared.css, packages/rollup/test/splitting.test.js, packages/test-utils/read-dir.js
Previously ref-counting for CSS file usage was just an incrementing number. This could lead to issues like #466 where a CSS file is incorrectly promoted to `common.css` because it is referenced in multiple places within a single bundle.
The new logic checks the number of **bundles** the CSS file appears in, and only puts the file into `common.css` if it's in more than one bundle.
=> Bundle specific ref-counting

docs/rollup.md, packages/rollup/README.md, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/splitting.test.js
Also fixes #485 by limiting output to a single file containing ALL compositions.
**BREAKING CHANGE**: The default file name when `json : true` has changed from whatever the CSS file was called to `exports.json`.
=> feat: Named json output

packages/svelte/src/markup.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/empty.html, packages/svelte/test/specimens/invalid-external-empty.html, packages/svelte/test/specimens/invalid-inline-empty.html, packages/svelte/test/svelte.test.js
Fixes #512, see the issue for the background & investigation.
This only runs the regex replacement if there's anything to replace, and also cleans up some of the error/warning output. As a bonus it also simplifies a lot of the error case test code & cuts down on the number of test cases by a bit.
=> fix: modular-css-svelte handles empty CSS files

package-lock.json, packages/rollup/README.md, packages/rollup/package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js
Fixes #516 (for rollup at least, more bundlers later if folks want 'em!)
This adds a new option to `@modular-css/rollup`, `dev`. Enabling dev mode will make the default exports of each CSS file a JS Proxy that throws whenever a non-existent property is read. Should be much easier to spot the **VERY LOUD REFERENCE ERRORS** vs trying to find instances of `class="undefined"`, right?
That's the theory anyways!
This also fixes the rollup peerDependency so it stops complaining about rollup `0.66.0` and up.
=> feat: dev mode for rollup

packages/processor/processor.js, packages/processor/test/__snapshots__/options.test.js.snap, packages/processor/test/options.test.js, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/svelte/src/markup.js, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/svelte.test.js, packages/test-utils/logs.js
Add new `verbose` option to rollup & svelte packages, also adds tests for the existing `verbose` option to processor package.
Fixes #520, though without using `npmlog` because it's more complicated than I need right now.
=> feat: Add verbose option to rollup & svelte

package-lock.json, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/external-with-values.css, packages/svelte/test/specimens/external-with-values.html, packages/svelte/test/svelte.test.js
Fixed an issue where the Regex over a component in svelte's
preprocessing would try to turn a single value (in this case, an @value
for something like a color) into an array-joined-string of classes.
Values don't necessitate that logic, so I've added a check to
branch based on whether or not the css key is an array.
If you'd like me to open an issue for this to reference this commit to, let me know!
=> Fix: Replace standalone value references in templates

package-lock.json, package.json, packages/processor/processor.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/processor/test/api.test.js, packages/rollup/package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/splitting.test.js, packages/test-utils/rollup-code-snapshot.js
Had to change how the plugin reported dependencies, as well as invent a new way of marking files as being replaceable in `processor.invalidate()`. Used to just `.remove()` them but the `transform` hook isn't getting called for unchanged files again, presumably due to the caching layer.
This has the downside of never removing files when they've been deleted/renamed, but I think that's probably ok? We'll see! At the very least it won't be a breaking change to add functionality to check for the file on disk when the `watchChange` event fires and then removing files that are gone after we've invalidated them.
=> feat: Rollup@1.0 support

package-lock.json, packages/rollup/package.json, packages/rollup/parser.js, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/multiple-chunks/a.js, packages/rollup/test/specimens/multiple-chunks/b.js, packages/rollup/test/specimens/multiple-chunks/d.css, packages/rollup/test/specimens/multiple-chunks/d.js, packages/rollup/test/specimens/multiple-chunks/e.js, packages/rollup/test/splitting.test.js
Another day, another big reshuffling of all this logic. I'll get it right someday, right?
This fixes #536 along with a host of other bugs that were preventing source maps from even being close to working. This requires a lot of flopping around to get right & work around limitations in what rollup gives us for asset details and limitations in the asset API (like not being able to get the hash until the file is written, but needing the hash for the final name when calling postcss...). It's inelegant and starting to get crazy-looking but it's functional and the tests are at least pretty thorough at this point.
😥
=> fix: clean up rollup chunk naming & source maps

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/specimens/stripped-dynamic-imports/a.js, packages/rollup/test/specimens/stripped-dynamic-imports/b.js, packages/rollup/test/splitting.test.js
Working around https://github.com/rollup/rollup/issues/2659
Without this change if you have any dynamic imports in your codebase that can be dropped by treeshaking you'll get JS errors like the following:
```
[!] (@modular-css/rollup plugin) TypeError: Cannot destructure property `modules` of 'undefined' or 'null'.
TypeError: Cannot destructure property `modules` of 'undefined' or 'null'.
at usage.overallOrder.forEach (node_modules\@modular-css\rollup\rollup.js:199:68)
at Array.forEach (<anonymous>)
at Object.generateBundle (node_modules\@modular-css\rollup\rollup.js:196:34)
at \node_modules\rollup\dist\rollup.js:16609:25
```
Added specimens and a test to the rollup code-splitting tests to ensure it no longer throws an error.
=> fix: don't explode when dynamic imports are removed by tree-shaking

packages/rollup/README.md, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/splitting.test.js
Adds a new option, `meta`, to the rollup plugin that will trigger it to write out a JSON file containing metadata about each JS chunk. Currently it only writes out CSS dependencies, but someday it might do more.
Fixes #540
Added a test
=> Add chunk CSS dependency metadata option

packages/rollup-rewriter/rewriter.js, packages/rollup-rewriter/test/__snapshots__/rewriter.test.js.snap, packages/rollup-rewriter/test/rewriter.test.js, packages/rollup-rewriter/test/specimens/no-asset-imports/a.css, packages/rollup-rewriter/test/specimens/no-asset-imports/a.js, packages/rollup-rewriter/test/specimens/no-asset-imports/b.css, packages/rollup-rewriter/test/specimens/no-asset-imports/b.js, packages/rollup-rewriter/test/specimens/no-asset-imports/c.css, packages/rollup-rewriter/test/specimens/no-asset-imports/c.js, packages/rollup-rewriter/test/specimens/no-asset-imports/d.js
Don't try and rewrite `import()` statements if the chunk doesn't have any assets that need loading.
Don't want to bloat up bundles with useless code, and `@modular-css/rollup` only tags bundle with `.assets` when they actually have assets. Can lead to errors when `rollup-rewriter` tries to call `assets.map` and `assets` is `undefined`.
Tests! Also ran it against a big project that first surfaced this behavior.
=> fix: limit import() rewrites

packages/rollup-rewriter/formats/amd.js, packages/rollup-rewriter/formats/es.js, packages/rollup-rewriter/formats/system.js
`@modular-css/rollup-rewriter` advertises support for a `loader` option, but it wasn't actually pumped through to the different format rewriters.
I want to use a custom `loader`, but couldn't.
Tests already existed, but just tested for the defaults. Now at least they're fully-testing that codepath.
=> fix: properly support loader option

packages/processor/plugins/values-replace.js, packages/processor/test/__snapshots__/values.test.js.snap, packages/processor/test/values.test.js
`\bval\b` will match "-val" which is a problem for folks using hyphens to separate classes. Now using `^val$` which when combined with postcss-value-parser should match almost everything the old one did but w/o being too greedy.
Fixes #548
Added a test with a bunch of permutations seen in CSS values/@media, manually verified that they all transform correctly after this change.
=> fix: use a safer regex for finding @values

package-lock.json, packages/svelte/package.json, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/multiple-link.html, packages/svelte/test/specimens/multiple-url.html, packages/svelte/test/specimens/simple2.css, packages/svelte/test/specimens/url.html, packages/svelte/test/svelte.test.js
- Adds a warning if there are multiple `<link>` elements in a file, processes only the first
- Ignores <link> elements when the `href` attribute is a URL
- Early-out if all the `<link>` elements are to URLs
- Removes trailing newlines when stripping out replaced `<link>`, which looks nicer
Wanted to be able to mix local `<link>` that should be transformed with external CSS that shouldn't be.
Tests!
=> fix: ignore URLs in <link href> 

packages/processor/processor.js, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/external.js
Modules flagged using `external` were throwing a wobbily, so now we filter 'em out.
I've got a project that uses `external` and it was breaking.
Added a test, also it doesn't break in my other project.
=> fix: ignore external modules

packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/svelte.test.js, packages/www/src/guide/usage-svelte.md
The svelte preprocessor can now take a `processor` arg. Also the test coverage around file invalidation for `<style>` is improved!
I like good tests & 100% coverage makes me feel warm and fuzzy even if it's mostly worthless.
I wrote tests for it! They even pass!
=> feat: svelte processor arg & improved test coverage

packages/glob/test/__snapshots__/glob.test.js.snap, packages/processor/plugins/composition.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/svelte/test/__snapshots__/svelte.test.js.snap
```diff
.foo {
-    
color: fuschia;
}
``` 
I always hated that extra newline but never took the time to get rid of it.
Updated a whoooooooole bunch of snapshots.
=> fix: remove newlines left over after deleting composes declarations

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/file-extension/entry.js, packages/rollup/test/specimens/file-extension/style.cssx
Don't use the source file's original extension, it may not be `.css` and that does bad things.
See https://5c5a73dabd66690008908a73--m-css.netlify.com/ for an example of the "bad things" I'm referring to 🤨
In this case it was the svelte plugin's support for inline `<style>` tags, meaning that a bunch of `.html` files were generated containing CSS. Most web servers handle content-type by file extension, so this went poorly.
Added a test, also ran https://m-css.com locally & verified that this fixed the issue.
=> fix: force rollup output to use .css

packages/processor/processor.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/processor/test/api.test.js, packages/processor/test/specimens/overlapping/entry1.css, packages/processor/test/specimens/overlapping/entry2.css, packages/processor/test/specimens/overlapping/tier1.css, packages/processor/test/specimens/overlapping/tier2.css, packages/processor/test/specimens/overlapping/tier3.css, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/overlapping/entry1.html, packages/svelte/test/specimens/overlapping/entry2.html, packages/svelte/test/specimens/overlapping/tier1.css, packages/svelte/test/specimens/overlapping/tier2.css, packages/svelte/test/specimens/overlapping/tier3.css, packages/svelte/test/svelte.test.js, packages/webpack/test/webpack.test.js
Ensure that walking the tree has completed before allowing exports/dependency information to be flattened.
If you called `processor.string()` or `processor.file()` on two files with shared dependencies w/o waiting for the first file to complete it's walk of the tree you could get random errors that made no sense.
Added a svelte & non-svelte test for it.
=> fix: dependency processing race condition

packages/webpack/loader.js, packages/webpack/test/__snapshots__/webpack.test.js.snap
Added the ability to use the style string like so:
```
import { styles } from "./styles.css";
```
This feature is present in the rollup plugin (https://github.com/tivac/modular-css/blob/1a84b5d7ee5d0b95160059ebc3c6f604dc2524ec/packages/rollup/rollup.js#L134), but not in webpack.
We want the ability to use the style string directly so we can insert it into the DOM wherever we want. We use ShadowDOM from time to time, so we want the ability to insert styles inside ShadowDOM.
=> Include Style String in Webpack Loader Output

packages/processor/processor.js
When invalidation was added in #532 I apparently forgot to account for it withiin the dependency walking code, so invalidated files wouldn't ever be rewalked.
This has likely been causing a variety of nasty-to-debug errors in the wild :disappointed:
See #572, the added test in `watch.test.js` is how I discovered this was broken.
=> fix: walk invalidated dependencies

packages/processor/plugins/values-composed.js, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/rollup.test.js.snap, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/rollup.test.js
When a `{css.fooga}` reference (or just `css.fooga` in `<script>` blocks) is found, it's now replaced with `"css.fooga"`.
So that svelte generates less code and the code it does generate doesn't explode. There's still `strict` mode if you want explosions though!
This helps #571 but I'm not sure it fixes it completely.
Added tests!
=> feat: replacing missing css.fooga with stringified version

packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/invalid-external-script.html, packages/svelte/test/specimens/invalid-external-template.html, packages/svelte/test/specimens/invalid-inline-script.html, packages/svelte/test/specimens/invalid-inline-template.html
Make sure that multiple `{css.key}` values will be replaced if they don't exist in referenced CSS.
Fixes #575 
Updated specimens & snapshots, saw it fail to replace multiple values. Updated `svelte.js` and now they're correctly replaced.
=> fix: replace multiple missing values

packages/rollup-rewriter/rewriter.js, packages/rollup-rewriter/test/__snapshots__/rewriter.test.js.snap, packages/rollup-rewriter/test/rewriter.test.js, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/dynamic1.css, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/dynamic1.js, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/entry1.css, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/entry1.js, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/entry2.css, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/entry2.js, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/static1.css, packages/rollup-rewriter/test/specimens/dynamic-shared-imports/static1.js
At dayjob :tm: a coworker ran into an issue where a dynamically loaded chunk that was being rewritten to include its CSS deps some of those deps were missing. Turns out that `@modular-css/rollup-rewriter` didn't include the CSS required by any static `imports` contained within the dynamic import chunk entry point.
So now it does.
Dynamic chunk entrypoints that have static dependencies that include CSS should be properly loaded.
Added specimens & a test. Verified it failed before this change, then passes afterwards.
=> fix(rollup-rewriter): include static dependencies

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/watch.test.js.snap
Instead of injecting `import` statements use `this.addWatchFile(<file>)` like rollup intended.
Solves some weird chunking issues I was seeing and is generally **way** more correct across the board.
Existing tests around chunking and watching still pass.
=> fix(rollup): properly include dependencies

packages/stylelint-config/.npmignore, packages/stylelint-config/LICENSE, packages/stylelint-config/README.md, packages/stylelint-config/package.json, packages/stylelint-config/stylelint.js
Adding a new package, `@modular-css/stylelint-config` to make it easy to have stylelint ignore the modular-css custom syntax using its `extends` support.
I don't want to keep on having to do this manually every time I start a new project using stylelint & modular-css.
Been using these properties as part of our broader stylelint config on a project for over a year. Extracted from that and then tested within that project.
=> feat(stylelint-config): add @modular-css/stylelint-config package

lerna/outdated.js, package.json, packages/www/package-lock.json
`npm outdated` run in every package is full of noise from bootstrapped packages, this is much more minimal and useful.
=> chore: add custom outdated script

packages/processor/test/__snapshots__/composition.test.js.snap, packages/processor/test/composition.test.js, packages/www/src/guide/feature-composing-styles.md, parsers/composes.pegjs, parsers/shared.pegjs
This is nice feature in css-modules, for doing quick composition of global classes. `global` acts as a keyword instead of a file here
Parses `composes: a, b, c from global` as `composes: global(a), global(b), global(c)`
Css-modules supports this, and it is nicer syntax when working with lots of global classes, such with bootstrap utility classes
added a test. I could get the current tests to pass locally tho, perhaps i'm setting the repo up wrong? did `lerna bootstrap` in the root, assuming that was enough.
=> feat: support from global for composes

package-lock.json, package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap
Using `this.emitFile()` for all file emission from the rollup plugin.
`this.emitFile()` is the correct future-proof way to emit files from rollup plugins. `this.emitAsset()` and `this.emitChunk()` are being deprecated, and it was never *really* supported to add files directly to the bundle the way they were.
Normal test suite
=> fix: use this.emitFile() API from rollup

packages/processor/README.md, packages/processor/processor.js, packages/processor/test/__snapshots__/options.test.js.snap, packages/processor/test/options.test.js
Implements options to disable value export, as mentioned in  #672.
Added unit test for option.
=> feat: option to suppress value export

package-lock.json, package.json, packages/processor/processor.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/processor/test/api.test.js, packages/svelte/package.json, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/link-resolving.html, packages/svelte/test/svelte.test.js, packages/www/src/api/usage-js.md
Exposed previously private(ish) `processor._resolve()` as `processor.resolve()` so it's obvious that it's fine and reasonable for consumers to use it.
Fixes #679 by allowing the svelte preprocessor to use the exact same file resolution logic as the core `modular-css` package.
Added a new svelte test, all existing tests still pass.
=> feat(processor): add processor.resolve()

package-lock.json, packages/svelte/package.json, packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/unquoted.html, packages/svelte/test/svelte.test.js
Warn users whenever an unquoted `class={css.foo}` is discovered.
The svelte preprocessor can create subtle bugs in cases where the user types something like `class={css.foo}`, this is fine assuming that `css.foo` is replaced with a single class but fails **hard** if there's any composition involved.
**Single-class case ✔**
```diff
-<div class={css.foo}>
+<div class=foo>
```
which is treated by the browser as `<div class="foo">`
**Multi-class case 💀**
```diff
-<div class={css.fooandbar}>
+<div class=foo bar>
```
which is treated by the browser as `<div class="foo" bar>`, which is definitely a problem.
More background on unquoted attributes is available from [Mathias Bynens](https://mathiasbynens.be/notes/unquoted-attribute-values).
Added tests!
=> feat(svelte): warn on unquoted class attributes

packages/processor/processor.js
when passing custom plugins you may get messages that don't have this key
=> fix: don't assume `plugin` key on messages

packages/aliases/aliases.js, packages/browserify/browserify.js, packages/cli/cli.js, packages/glob/glob.js, packages/paths/paths.js, packages/postcss/postcss.js, packages/postcss/test/postcss.test.js, packages/processor/lib/message.js, packages/processor/lib/output.js, packages/processor/plugins/values-export.js, packages/processor/plugins/values-replace.js, packages/processor/processor.js, packages/rollup-rewriter/rewriter.js, packages/rollup/rollup.js, packages/webpack/loader.js, packages/webpack/plugin.js, packages/www/build/svelte.js, packages/www/src/api/usage-svelte.md
Using `{ __proto__ : null }` and object spread everywhere.
Never liked the `Object.assign()` flow all that much, and while using it + `Object.create(null)` is technically more correct than `{ __proto__ : null }` until someone *actually deprecates* `__proto__` I think it's plenty clear and looks nicer.
All tests pass.
=> refactor: Bye Object.assign

packages/webpack/package.json, packages/webpack/plugin.js, packages/webpack/test/records/parse-error.js.json, packages/webpack/test/specimens/parse-error.css, packages/webpack/test/specimens/parse-error.js, packages/webpack/test/webpack.test.js
Turns out that even if a loader throws an error webpack will still happily fire the `emit` event to plugins. Unclear why, but needed to add some bomb-proofing there so that `@modular-css/webpack/plugin` wouldn't try to generate output from invalid input files that had already errored out.
Fixes #724 
Ran tests locally, also, Travis.
/CC @chiel
=> fix(webpack): don't try to emit if there were errors

packages/svelte/svelte.js, packages/svelte/test/specimens/link-component.html, packages/svelte/test/svelte.test.js
Remove the `i` flag from the regex that matches `<link>` so it can't match `<Link>`
Fixes #711 
Added a test
=> fix(svelte): case-sensitive matching on <link>

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/__snapshots__/watch.test.js.snap, packages/rollup/test/rollup.test.js
Using `this.getModuleInfo()` plugin hook to get better information about the module graph so it can be fully traversed, to ensure that all CSS are properly represented and can be chunked correctly.
Tired of CSS missing from complicated chunking setups
Added tests, also verified against work codebase which is *very* complex and suffered from this bug.
=> fix(rollup): walk full tree for dependencies

packages/rollup-rewriter/rewriter.js, packages/rollup-rewriter/test/__snapshots__/rewriter.test.js.snap, packages/rollup-rewriter/test/rewriter.test.js, packages/rollup-rewriter/test/specimens/external-import/a.css, packages/rollup-rewriter/test/specimens/external-import/a.js, packages/rollup-rewriter/test/specimens/external-import/c.css, packages/rollup-rewriter/test/specimens/external-import/c.js
Check to make sure a chunk is actually a thing before trying to read assets off of it.
Fixes #688
=> fix(rewriter): don't explode on external chunks

packages/processor/test/__snapshots__/composition.test.js.snap, packages/processor/test/composition.test.js, parsers/shared.pegjs
Support for more valid classnames, helpful with tailwindCSS which uses classes like `hover:bg-red`
implementation borrowed mostly from https://github.com/pegjs/pegjs/blob/v0.10.0/examples/css.pegjs
=> feat: Support escaped characters in composed class names

packages/processor/plugins/composition.js, packages/processor/test/__snapshots__/composition.test.js.snap, packages/processor/test/composition.test.js
Only remove the entire rule if `composes` is the only declaration within it.
Fixes #768
Added a bunch of tests
=> fix: remove rule if there's no other decls

packages/processor/plugins/scoping.js, packages/processor/test/__snapshots__/keyframes.test.js.snap, packages/processor/test/keyframes.test.js
Early-out from scoping when the parent of the node is a `@keyframes` block.
https://m-css.com/repl/#NrBEHoFsEMEsDsB0BjAzq0AaUABA1gKYCeAZgE7SQGoAEJA9vTQN4A68NrALgAyICMAVgCkLdjQmSJyegBt6ZAFw0yBACYBucZIC+7HaAC6hoA
Added a test.
=> fix(processor): don't scope @keyframes contents

packages/svelte/svelte.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/invalid-external-empty.html, packages/svelte/test/svelte.test.js
+ Modify existing test against empty css files to also test against this - I am happy to split this into its own test if that is preferred.
+ Add word boundary (`\b`) selectors to ensure that we don't have collisions of advancingly specific class names when they are all undefined (for example, if you had both `.foo` and `.foobar` referenced in template, yet both are undefined in css, that will cause this error).
https://github.com/tivac/modular-css/issues/780
test added.
=> fix(svelte): Match missed classes to word boundaries (#780)

packages/vite/vite.js
Fixed `resolveId` hook in the vite plugin to properly resolve files, so that `load` hook doesn't need to duplicate the work.
`@modular-css/vite` didn't work when serving on non-win32 platforms due to vite file resolution sending in both absolute files as well as relative files that *look* absolute (like `/src/bar.mcss`). vite plugin had logic to handle that, but it didn't work quite right.
Run both m-css.com and the vite-mcss-tester repo against this new code in win32 & Ubuntu (via WSL2)
=> fix(vite): non-win32 file resolution

packages/svelte/script.js, packages/svelte/test/__snapshots__/svelte.test.js.snap, packages/svelte/test/specimens/script-multiple.svelte, packages/svelte/test/svelte.test.js
At least until a matching import is found, still bail on the first one for optimization simplicity reasons.
Fixes #818
Added a test
=> feat(svelte): check every <script>

packages/css-to-js/css-to-js.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/rollup.test.js, packages/rollup/test/specimens/multiple-composition/multiple-composition.css, packages/rollup/test/specimens/multiple-composition/multiple-composition.js, packages/rollup/test/specimens/multiple-composition/other.css
Because it can cause invalid output if they get moved ahead of their dependencies, and we don't need to handle them at this point anyways.
=> fix: don't move composed classes early

.changeset/old-bugs-sell.md, packages/css-to-js/css-to-js.js, packages/css-to-js/test/api.test.js
Since the module already had to normalize paths to be absolute it will now use those absolute paths internally when looking up information from the `Processor` instance.
Previously `@modular-css/css-to-js` would use the path as passed to it, which could cause issues with bundlers that passed relative paths (usually because of the use of aliases). 
Updated tests
=> fix: always use normalized path

.changeset/nine-apples-share.md, packages/webpack/plugin.js, packages/webpack/test/webpack.test.js
Fix for webpack's watch mode.
Webpack plugin throws `Unknown file: ...` on non-css file change.
https://github.com/tivac/modular-css/blob/3d4b600947662a718fa1a3e7e99692ee0a80ae1a/packages/webpack/plugin.js#L23-L25
New unit test has been added.
=> Do not invalidate non css files

.changeset/giant-garlics-worry.md, packages/processor/processor.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/processor/test/__snapshots__/composition.test.js.snap, packages/processor/test/composition.test.js, packages/processor/test/specimens/composes.css, packages/processor/test/specimens/composes2.css, packages/processor/test/specimens/folder/folder2.css
Currently a technically the same composition of multiple classes from other file gives slightly different composition information depending on how it has been declared.
<details>
<summary>Multiple composes</summary>
```css
// composes.css
.class {
composes: someDep from 'lib';
composes: anotherDep from 'lib';
}
```
give
```json
"composes.css": {
"composes": [
"anotherDep",
"someDep",
"class",
],
```
</details>
<details>
<summary>Single compose</summary>
```css
// composes.css
.class {
composes: someDep, anotherDep from 'lib';
}
```
gives 
```diff
"composes.css": {
"composes": [
-  "anotherDep",
"someDep",
+   "anotherDep",
"class",
],
```
</details>
For sake of consistency. It gives an idea of order in which classes have been declared and it can be used for post-processing.
Unit tests …
=> Improve consistency of composition map

.changeset/warm-dryers-thank.md, packages/css-to-js/css-to-js.js, packages/css-to-js/test/__snapshots__/api.test.js.snap, packages/css-to-js/test/api.test.js, packages/css-to-js/test/specimens/composes/custom-between-rules.css, packages/css-to-js/test/specimens/composes/custom-first-rule.css
Hello 👋 I've spotted an issue with `css-to-js` module. [For CSS](https://github.com/plesiecki/modular-css/blob/df11a5be29fc66516de7ae60836a9adf515f61cd/packages/css-to-js/test/specimens/composes/custom-between-rules.css#L1-L9):
```css
.rule { 
display: flex;
}
.custom {
color: pink;
}
.rule {
composes: custom;
}
```
it produces an [invalid JS](https://github.com/plesiecki/modular-css/blob/df11a5be29fc66516de7ae60836a9adf515f61cd/packages/css-to-js/test/__snapshots__/api.test.js.snap#L61) which looks like this:
```js
const rule =  + " " + "mc9c938a76_rule"
```
A valid CSS can give an invalid JS.
Unit tests have been updated.
**For the second test a snapshot have been updated manually so the test should fail.**
=> [css-to-js] Invalid JS when mixing rules with composes

.changeset/chatty-turtles-look.md, packages/css-to-js/css-to-js.js, packages/css-to-js/test/__snapshots__/api.test.js.snap, packages/css-to-js/test/api.test.js, packages/webpack/README.md
New option for `css-to-js` to change a kind of variable declaration, defaults to `const`.
Some folks still have to support ES5, thus `const` declarations within JS output may not help.
Naturally, we can process modules by an additional loader (e.g. babel-loader) but it involves significant overhead.
To avoid extra loaders I'd like to introduce a new option.
Unit tests have been updated.
=> [css-to-js] option to change type of variable declaration

packages/css-to-js/css-to-js.js, packages/css-to-js/test/__snapshots__/api.test.js.snap, packages/css-to-js/test/api.test.js, packages/rollup/README.md, packages/vite/README.md, packages/webpack/README.md
Webpack loader sets the `defaultExport` option.
https://github.com/tivac/modular-css/blob/f37b5a786259eacae45b5cf68e4fe352af570af4/packages/webpack/loader.js#L5-L21
Options are handed over to the `css-to-js` module and then nothing is done about `defaultExport`.
Handle `defaultExport` option just like any other option set by webpack loader.
Unit tests have been updated.
=> [css-to-js] Handle `defaultExport` option

.changeset/tricky-cats-fail.md, packages/processor/plugins/values-replace.js
Small optimization to `@value` replacement, only call `.toString()` on the parsed value if it was dirtied.
Speeeeed.
Tests.
=> chore: only .toString() if dirty

.changeset/tidy-papayas-clap.md, packages/processor/plugins/values-import.js, packages/processor/test/__snapshots__/values.test.js.snap, packages/processor/test/specimens/deep-namespace/a.css, packages/processor/test/specimens/deep-namespace/b.css, packages/processor/test/specimens/deep-namespace/c.css, packages/processor/test/values.test.js
Updating the internal value mapping after handling imported `@value`s.
Fixes #964
I added a test that fails before the fix.
=> Fix: namespace import referencing via value aliases

.changeset/angry-shoes-double.md, packages/processor/processor.js, packages/processor/test/__snapshots__/api.test.js.snap, packages/processor/test/api.test.js, packages/vite/vite.js
Working to make vite reloading more reliable, especially around dependencies. Also fixing an issue that could leave stale compositions around when re-running the processor against invalidated files.
vite reload behavior has been extremely annoying at my day job.
Manual testing _only_ so far.
=> Vite updates & invalidation fixes

.changeset/little-beers-cheer.md, packages/css-to-js/css-to-js.js, packages/css-to-js/test/__snapshots__/api.test.js.snap, packages/css-to-js/test/api.test.js, packages/processor/plugins/before/values-local.js, packages/processor/plugins/values-import.js, packages/webpack/test/__snapshots__/webpack.test.js.snap
Changed things up to make sure that `@value`s are exported, even when they're an alias to an imported name spaced `@value`.
I also made sure that the exported JS ends with semicolons because I can't believe I never did that before 😒
Fixes #982 
Added a test.
=> fix: Ensure that aliased values get exported

.changeset/empty-tools-happen.md, packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap
JSON output for webpack package outputted arrays of classes, this change will join the classes into strings, matching behavior in m-css/rollup package.
=> fix: Join class compositions for webpack JSON output

.changeset/pretty-camels-breathe.md, packages/processor/lib/value-replacer.js, packages/processor/plugins/values-import.js, packages/processor/plugins/values-replace.js, packages/processor/test/__snapshots__/values.test.js.snap, packages/processor/test/specimens/namespace-expansion/a.css, packages/processor/test/specimens/namespace-expansion/b.css, packages/processor/test/specimens/namespace-expansion/c.css, packages/processor/test/values.test.js
Previously we were only doing a simple like-for-like match inside of `values-import.js`, now it actually parses the values and replaces them using the same logic that the `values-replace.js` plugin uses.
Fixes #1020 
Added a test, existing tests passing
=> fix: Properly replace @values inside of other @values

.changeset/three-yaks-hug.md, package-lock.json, packages/processor/processor.js, packages/rollup/test/__snapshots__/splitting.test.js.snap
If available, use the node v22 API to enable the v8 compiler cache.
ESLint saw improvements of 90% in startup times, we want in on that.
https://bsky.app/profile/humanwhocodes.com/post/3lnvcvv5p6a25
Normal tests all passing, including in playwright
=> feat: attempt to enable v8 compiler caching
