src/plugins/scoping.js, test/plugin-scoping.js
And fix up `:global()` support while I'm in there.
=> Add pseudo class tests

src/plugins/composition.js, test/plugin-composition.js
```css
.wooga {
composes: global(booga);
}
```
Also simplified composition tests by making a message helper to get things a bit more DRY
=> Add support for composes: global(selector);

package.json, src/browserify.js
Instead of manually buffering streams, let a module handle that for us!
=> Use sink-transform

src/processor.js, test/processor.js, test/results/browserify-avoid-duplicates-local.js, test/results/browserify-avoid-duplicates-start.js, test/results/browserify-export-identifiers.js, test/results/browserify-include-css-deps.js
Also updated tests so they, you know, pass.
=> Change exports to be space-separated strings

README.md, index.js, package.json, src/_promise.js, src/browserify.js, src/plugins/_values.js, src/processor.js, test/browserify.js, test/issues.js, test/processor.js, test/specimens/invalid.js
Fixes #38 
Totally changes Processor API, so caveat emptor!
=> Async plugins

src/browserify.js, src/processor.js, test/factor-bundle.js, test/issue-58.js, test/lib/bundle.js, test/results/issues/58.css, test/specimens/issues/58/1.css, test/specimens/issues/58/2.css, test/specimens/issues/58/issue.css, test/specimens/issues/58/other.css, test/watchify.js
"Smarter" is an interesting choice of words, but this fixes the "inject require statements" kludge in a more-correct way that actually involves a TON of code.
So not really sold that this is a good idea, but it is working! That's somethin!
=> Smarter watchifying

src/browserify.js, test/factor-bundle.js, test/processor.js, test/results/factor-bundle/relative/b.css, test/results/processor/output-all.css, test/specimens/factor-bundle/relative/b.js, test/specimens/node_modules.css, test/specimens/node_modules/styles/package.json, test/specimens/node_modules/styles/styles.css, test/util-composition.js
It's less unexpected from a browserify plugin, IMO.
=> Local transforms only

src/browserify.js, test/browserify.js, test/results/browserify/export-all-identifiers.json, test/specimens/multiple.css
Fixes #68
Also switched to more-complete paths instead of the weird basedir shorthand.
=> Ensure that JSON output is strings

bin/cli.js, package.json
And also expose it so that npm will generate the alias for us.
Fixes #70
=> Fix CLI bit-rot

src/browserify.js
See #90 for the other part of this
=> Sort JSON output by file as well

src/processor.js, src/rollup.js, test/processor.test.js
For easier access both internally and externally.
Fixes #117
=> Add compositions to .output()

test/processor.test.js, test/results/processor/unicode.css, test/specimens/processor/unicode.css
=> Add unicode test for processor

package.json, src/browserify.js, src/lib/message.js, src/plugins/_values.js, src/plugins/composition.js, src/processor.js, src/rollup.js, test/plugin.composition.test.js, test/plugin.scoping.test.js, test/plugin.values-composed.test.js, test/plugin.values-local.test.js, test/rollup.test.js
`Object.assign` is fine, use it instead.
=> Remove lodash.assign

src/plugins/_values.js, test/plugin.values-local.test.js, test/processor.test.js
Previously only @media blocks were affected. Now it'll hit @value rules too. Also added some arrow fns where it helped legibility.
=> Replace local @value entries in @value rules

package.json, src/plugins/scoping.js, test/plugin.scoping.test.js
But god help you if you cross the streams. Fixes #205
=> Global can overlap global, local can overlap local

package.json, src/lib/message.js, src/plugins/keyframes.js, src/plugins/scoping.js, test/keyframes.test.js, test/plugin.scoping.test.js, test/processor.test.js, test/rollup.test.js
=> Properly scope multiple animations in a single declaration

src/webpack.js, test/results/webpack/simple.js, test/webpack.test.js
This changes the loader used in the test to our own loader, which now transforms the code to a JS object.
Looking at https://github.com/webpack/css-loader/blob/master/lib/loader.js to understand what needs to be added.
=> CHANGE webpack loader into minimal working version

package.json
Closes #227
https://greenkeeper.io/
=> chore: update rollup to version 0.39.2

package.json, src/plugins/composition.js, test/plugin.composition.test.js
Fixes #238
This is a semver **major** change.
=> Make multiple composition a crime

package.json, packages/rollup/package.json, packages/www/.surgeignore, packages/www/CNAME, packages/www/gen/.gitignore, packages/www/index.html, packages/www/index.js, packages/www/package.json, packages/www/rollup.config.js, packages/www/style.css
Needs a real domain, currently lives at loud-yak.surge.sh
Shareable URLs, what should be full `modular-css` support, it's neat & already useful for reproing issues.
=> Add a simple site

package.json, packages/browserify/package.json, packages/core/package.json, packages/glob/package.json, packages/postcss/package.json, packages/rollup/package.json, packages/test-utils/package.json, packages/webpack/package.json
=> Update a bunch of packages

packages/core/README.md, packages/core/plugins/scoping.js, packages/core/test/__snapshots__/plugin.scoping.test.js.snap, packages/core/test/plugin.scoping.test.js
Ref https://github.com/tivac/modular-css/issues/284
=> feat: exportGlobals option in core

packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/webpack.test.js
=> Incremental build

packages/core/lib/resolve.js, packages/core/processor.js, packages/core/test/api.test.js, packages/core/test/composition.test.js, packages/core/test/values.test.js
Ref #297 
Recursion with state mutating can be dangerous sometimes :)
=> Recursive remove

packages/core/processor.js
#306 was a good idea but a terrible implementation. This fixes all the problems I could find so far.
Like it actually works, which seems important.
=> Rework .remove(), again

packages/test-utils/package.json, packages/test-utils/relative.js
It requires copying a single function & regex, but seems worth it.
=> refactor: remove dep cycle

.travis.yml, package-lock.json, package.json
Fixes #317, also includes npm5 lockfile to prep for that whole thing.
=> Use lint-staged to check & fix commits 

package.json
=> update danger to version 1.1.0

.travis.yml, package-lock.json, package.json, packages/core/package.json, packages/postcss/package.json, packages/rollup/package.json, packages/rollup/test/rollup.test.js, packages/webpack/package.json, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/www/package.json
=> chore: update jest to version 21.0.2

packages/aliases/package.json, packages/browserify/package.json, packages/browserify/test/__snapshots__/watchify.test.js.snap, packages/browserify/test/watchify.test.js, packages/paths/package.json, packages/rollup/test/rollup.test.js, packages/svelte/test/__snapshots__/rollup.test.js.snap, packages/webpack/test/webpack.test.js
=> Package updates 02162018

.travis.yml
https://github.com/bluzi/travis-buddy
Seems like a neat idea, let's give it a shot!
=> Add TravisBuddy

package-lock.json, package.json, packages/rollup/README.md, packages/rollup/package.json, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap
I requested it in https://github.com/rollup/rollup/issues/2383, @guybedford added it in https://github.com/rollup/rollup/pull/2405, and now I get to delete a bunch of complicated code!
🎉👏🏻🎉 @guybedford 🎉👏🏻🎉
=> Use rollup@0.65.0's watchChange event

packages/webpack/README.md, packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/webpack.test.js
=> Update Webpack plugin to accept existing processor, and add test.

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/specimens/circular-dependencies/a.css, packages/rollup/test/specimens/circular-dependencies/a.js, packages/rollup/test/specimens/circular-dependencies/b.css, packages/rollup/test/specimens/circular-dependencies/b.js, packages/rollup/test/splitting.test.js
The `dependency-graph` instance used in the rollup plugin for tracking JS chunk usage of CSS files needed to have circular dependency support turned on.
Fixes #539 
Added test specimens that introduced a circular dependency, added test to run them, test passes after change and output looks correct.
=> Support circular dependencies

packages/rollup/rollup.js, packages/rollup/test/__snapshots__/splitting.test.js.snap, packages/rollup/test/specimens/metadata/a.css, packages/rollup/test/specimens/metadata/a.js, packages/rollup/test/specimens/metadata/b.css, packages/rollup/test/specimens/metadata/b.js, packages/rollup/test/specimens/metadata/c.js, packages/rollup/test/specimens/metadata/d.css, packages/rollup/test/specimens/metadata/d.js, packages/rollup/test/splitting.test.js
Filter dependencies before trying to map them to ensure that chunks w/ no CSS dependencies don't throw errors.
Fixes #543 
Included tests.
=> fix: support chunks that don't depend on css

package-lock.json, package.json, packages/rollup-rewriter/rewriter.js, packages/scratchpad/chunktest.js, packages/webpack/test/webpack.test.js, packages/www/src/repl/store.js
Just me flopping around for a bit...
=> Fix netlify deploys

packages/rollup/chunker.js
No signficant changes, just tidying up some after staring at this code a bunch recently.
I :eyes: at this code all day yesterday trying to find a bug (I couldn't, hooray) and noticed a few things that could've been better.
All the existing tests.
- [] Bug fix (non-breaking change which fixes an issue)
=> refactor(rollup): clean up chunking logic a bit

packages/www/package.json
=> chore(www): clean up some dependencies

jest.config.js, packages/svelte/test/__snapshots__/rollup.test.js.snap, packages/svelte/test/rollup.test.js, packages/svelte/test/specimens/inline-chunking/a-dep.css, packages/svelte/test/specimens/inline-chunking/a.html, packages/svelte/test/specimens/inline-chunking/b-dep.css, packages/svelte/test/specimens/inline-chunking/b.html, packages/svelte/test/specimens/inline-chunking/shared.css, packages/test-utils/expect/toMatchRollupAssetSnapshot.js
Just a test and some specimens.
I want to be sure it works, and this admittedly simple test seems to show that it does. I think there's still a bug rattling around in there somewhere but this is a start.
`npm test`
=> Add test for svelte <style> + rollup chunking

packages/rollup-rewriter/README.md, packages/rollup-rewriter/formats/amd.js, packages/rollup-rewriter/formats/es.js, packages/rollup-rewriter/formats/system.js, packages/rollup-rewriter/rewriter.js, packages/rollup-rewriter/test/__snapshots__/rewriter.test.js.snap, packages/rollup-rewriter/test/rewriter.test.js
Let the `loader` option be either a string or a function.
Allows for picking a file out of the bundle to be used, even if the output name is hashed by rollup.
Added tests.
=> feat(rollup-rewriter): let loader option be a function

package-lock.json, packages/www/package.json, packages/www/rollup.config.js
`rollup-plugin-alias` major update slipped past and totally broken things.
I want site builds to work.
Tested site builds locally, they function again.
=> fix(www): get site building again

package-lock.json, package.json, packages/browserify/package.json, packages/cli/package.json, packages/postcss/package.json, packages/processor/package.json, packages/rollup/test/__snapshots__/splitting.test.js.snap
Updated dependencies and fixed some errors that resulted.
Mostly to get latest `dependency-graph` change for more efficient graph traversal.
The usual ways.
=> chore: updating dependencies

package-lock.json, package.json, packages/rollup-rewriter/rewriter.js, packages/rollup/rollup.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/rollup/test/__snapshots__/watch.test.js.snap, packages/rollup/test/watch.test.js, packages/test-utils/expect/toMatchRollupAssetSnapshot.js, packages/test-utils/expect/toMatchRollupCodeSnapshot.js, packages/test-utils/expect/toMatchRollupSnapshot.js
- Removed usage of now-really-deprecated rollup features.
- Updated snapshots to match new rollup@2 output
Want to use rollup@2 and not get massively spammed with warnings.
Tested locally, obviously Jenkins will run as well.
=> feat(rollup): rollup@2 compatibility

package-lock.json, package.json, packages/rollup-rewriter/test/__snapshots__/rewriter.test.js.snap
=> chore: updated rollup & snapshots

packages/rollup-rewriter/package.json, packages/rollup/package.json
=> fix(rollup): update peerDep to rollup@2

.github/workflows/ci.yml
Windows actions seem busted with cache action v2, trying to fix it
=> chore: roll back to cache v1

package-lock.json, packages/cli/package.json, packages/postcss/README.md, packages/postcss/package.json, packages/postcss/postcss.js, packages/postcss/test/__snapshots__/postcss.test.js.snap, packages/postcss/test/postcss.test.js, packages/processor/package.json, packages/webpack/package.json
Upgrading all usage of `postcss` to version 8
postcss ecosystem is moving to 8, we should too
Ran all the tests!
=> chore: postcss@8 support

.github/workflows/ci.yml
=> chore: update actions

packages/www/svelte.config.js
Forgot I left this disabled while debugging some bundling issues, let's see if re-enabling it breaks anything!
=> chore(www): enable minification

packages/svelte/README.md
=> fix page jump

package.json, packages/www/src/routes/api/_content/usage-browserify.md, packages/www/src/routes/api/_content/usage-rollup.md, packages/www/src/routes/api/_content/usage-sveltekit.md, packages/www/src/routes/api/_content/usage-vite.md, packages/www/src/routes/api/_content/usage-webpack.md, packages/www/src/routes/api/_content/usage.md
They're the same as `vite`, but doesn't hurt to list it out and be specific.
Folks were asking for examples.
Builte site locally.
=> docs: add sveltekit docs

packages/svelte/link.js, packages/svelte/script.js
CodeQL flagged these, so making them a bit more flexible
=> fix: safer </script> regexes

packages/www/package.json, packages/www/svelte.config.js
Use `@modular-css/shortnames` in production builds
Smaller size to download
This PR's test deploy will do nicely
=> chore(www): shorter names in prod

package-lock.json, package.json, packages/css-to-js/css-to-js.js, packages/rollup/test/__snapshots__/rollup.test.js.snap, packages/webpack/README.md, packages/webpack/loader.js, packages/webpack/package.json, packages/webpack/plugin.js, packages/webpack/test/__snapshots__/webpack.test.js.snap, packages/webpack/test/records/change.js.json, packages/webpack/test/records/es2015-default.js.json, packages/webpack/test/records/es2015-named.js.json, packages/webpack/test/records/invalid-name.js.json, packages/webpack/test/records/invalid.js.json, packages/webpack/test/records/parse-error.js.json, packages/webpack/test/records/simple.js.json, packages/webpack/test/records/start.js.json, packages/webpack/test/records/watch.js.json, packages/webpack/test/webpack.test.js
`webpack@5` support for `@modular-css/webpack`. Backwards incompatible with webpack 2/3/4.
Fixes #848 
Tests, so not really very well at all.
=> feat: webpack@5

.changeset/perfect-kids-raise.md, package-lock.json, packages/vite/package.json, packages/vite/vite.js
- Bumps [vite](https://github.com/vitejs/vite) to ^3.0.3
- Modifies vite's module graph `updateModuleInfo` to use a new
(and larger) method signature
- new parameters are simply `null` since mcss doesn't support
partial hmr.
Svelte-kit, and by extension, vite, has moved up to v3 of Vite with sveltekit de-abstracting the vite config in projects. Modular css uses vite 2.x but upgrading sveltekit to use vite 3 means mcss should support vite 3.
Without this Change, Modular CSS wouldn't be able to be used with vite 3.x or svelte-kit as it stands currently because of peer dependency conflicts. 
This change introduces an updated call to viteServer's `moduleGraph.updateModuleInfo` that now takes additional parameters for "partial hmr"... whatever that means.
- [X ] Bug fix (non-breaking change …
=> fix(vite): bump modular-css/vite peerDependency "vite" to 3.x

.changeset/chilled-dragons-fetch.md, packages/processor/lib/identifiers.js, packages/processor/plugins/composition.js, packages/processor/test/composition.test.js, packages/www/src/routes/_home/home.mcss
=> feat: more composition errors

packages/processor/processor.js, packages/processor/test/__snapshots__/options.test.js.snap, packages/test-utils/expect/toMatchLogspySnapshot.js
=> fix: dupecheck _every_ file we track

.changeset/plenty-fireants-sleep.md, package-lock.json, packages/css-to-js/css-to-js.js, packages/css-to-js/test/__snapshots__/api.test.js.snap, packages/vite/tests/vite.spec.mjs
Generating invalid JS is bad mmkay.
=> fix: output valid JS for coverage
